SELECT * FROM DADOS_SENSORES;

SELECT 
    LEITURA,
    CULTURA_MONITORADA,
    UMIDADE_DO_SOLO,
    SITUACAO_DA_UMIDADE,
    STATUS_DA_BOMBA
FROM DADOS_SENSORES;

SELECT 
    STATUS_DA_BOMBA,
    COUNT(*) AS QUANTIDADE
FROM DADOS_SENSORES
GROUP BY STATUS_DA_BOMBA;

SELECT 
    AVG(UMIDADE_DO_SOLO) AS MEDIA_UMIDADE
FROM DADOS_SENSORES;

SELECT 
    LEITURA,
    UMIDADE_DO_SOLO,
    SITUACAO_DA_UMIDADE,
    VALOR_DO_LDR,
    SITUACAO_DO_PH,
    DECISAO_DO_SISTEMA
FROM DADOS_SENSORES
WHERE SITUACAO_DA_UMIDADE = 'Solo seco';